development:
  adapter: postgresql
  encoding: unicode
  database: fande_development
  username: user
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: fande_test
  username: user
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: fande_production
  username: user
  password: 
